#! /usr/bin/env ruby

require "bundler/setup"
require 'sinatra'
require 'polycard/card_controller'
require 'polycard/side_controller'

set :run, false

class Main < Sinatra::Base
  set :bind, '0.0.0.0'
  set :port, 8080

  use CardApp 
  use SideApp
end
Main.run!
